### ISSUE TITLE
Travis CI and GSL/NETCDF

### ISSUE THREAD

**Issue by chemphys** [paesanilab/potential_fitting#18]
@zonca I cannot find a way to use ncgen in travis. It is installed, but it complains that the command is not found. Also, it still doesn't find the gsl libs.

**Comment by zonca** [comment]
Please remove the testing from the pull request, let's review The pull
request testing just locally on our machines and then at the traverse on a
separate pull request

**Comment by zonca** [comment]
@chemphys can you please create a Pull Request with your attempt at making travis-ci working with your new tests? I'll take care of fixing it then. When you create the PR, make sure you check the box **allow edits from maintainers**
