### ISSUE TITLE
Polynomial generator min filter

### ISSUE THREAD

**Issue by agoetz** [paesanilab/potential_fitting#41]
Volodymyr's original code contains a filter for minimum order. Should correspond to this line

https://github.com/paesanilab/potential_fitting/blob/master/polynomial_generation/src/poly-gen_mb-nrg.pl#L582

Need to be supported and checked whether we can reproduce MB-pol 2B polynomials.

**Comment by chemphys** [comment]
Hey @agoetz , do you have the outputs from the polynomial generation for water? It would help if I can see the differences between vlodimirs code and the actual one.

Thanks!
