### ISSUE TITLE
Hardcoded values 1B single script

### ISSUE THREAD

**Issue by chemphys** [paesanilab/potential_fitting#47]
Hey @zonca ,

There are two values in the script that are hardcoded for BF4, [here](https://github.com/paesanilab/potential_fitting/blob/master/fitting/1B/get_codes/get-1b-fit.py#L83) and [here](https://github.com/paesanilab/potential_fitting/blob/master/fitting/1B/get_codes/get-1b-fit.py#L85). This should be fixed. The numbers needed are in the output of the polynomial generation.

**Comment by zonca** [comment]
do you mean `generate_input_poly.py`?

**Comment by chemphys** [comment]
Nope, is the [poly-gen_mb-nrg.pl](https://github.com/paesanilab/potential_fitting/blob/master/polynomial_generation/src/poly-gen_mb-nrg.pl) output. Right now it is not being saved. I think it is necessary to save it to a poly.log file, so we know how many terms of each degrees, and how many total terms and different variables we have in our polynomials.

This output is something like this:
```
<> molecules(2) <>

A1B2
A1B2

<> atoms (6) <>

Aa:Ba1:Ba2:Ab:Bb1:Bb2

<> permutations (8) <>

0:1:2:3:4:5
3:4:5:0:1:2
0:1:2:3:5:4
3:5:4:0:1:2
0:2:1:3:4:5
3:4:5:0:2:1
0:2:1:3:5:4
3:5:4:0:2:1

<> variables (15) <>

 0 :   A(a) <===>  B1(a) : x-intra-AB
 1 :   A(a) <===>  B2(a) : x-intra-AB
 2 :  B1(a) <===>  B2(a) : x-intra-BB
 3 :   A(b) <===>  B1(b) : x-intra-AB
 4 :   A(b) <===>  B2(b) : x-intra-AB
 5 :  B1(b) <===>  B2(b) : x-intra-BB
 6 :   A(a) <===>   A(b) : x-AA
 7 :   A(a) <===>  B1(b) : x-AB
 8 :   A(a) <===>  B2(b) : x-AB
 9 :  B1(a) <===>   A(b) : x-AB
10 :  B1(a) <===>  B1(b) : x-BB
11 :  B1(a) <===>  B2(b) : x-BB
12 :  B2(a) <===>   A(b) : x-AB
13 :  B2(a) <===>  B1(b) : x-BB
14 :  B2(a) <===>  B2(b) : x-BB

<> 1st degree <>

15 possible 1st degree monomials
3 <<== accepted 1st degree terms

<> 2nd degree <>

120 possible (filtered) 2nd degree monomials
21 <<== accepted 2nd degree terms

<> 3rd degree <>

680 possible (filtered) 3rd degree monomials
110 <<== accepted 3rd degree terms

<> 4th degree <>

3060 possible (filtered) 4th degree monomials
463 <<== accepted 4th degree terms

<> 5th degree <>

11628 possible (filtered) 5th degree monomials
1672 <<== accepted 5th degree terms

 Total number of terms: 2269
```
Here, the python script should read this file, and extract the `Total number of terms:` , which is `npoly`, and extract `<> variables `, which is `nvars`.

This way the user won't have to change anything.

**Comment by zonca** [comment]
ok, it looks reasonable, I think it is worth for me to spend time on Python scripting if it is something really complicated or if it is something that needs some initial design. This task doesn't look either, can you assign someone else?

**Comment by fpaesani** [comment]
I think that everything is important at this point, even if it looks simple. 
@zonca, I feel that you have to find something you can contribute since it looks like @chemphys is now taking over what you were have been working on for the past year.

**Comment by chemphys** [comment]
@fpaesani , @zonca I will take care of this one. Now I have a sample script of how to run everything, I can do the same for 2B and improve it.

**Comment by fpaesani** [comment]
@zonca if you can be of help, that should always come first, especially if it is relatively easy, independently of our own projects. Thanks!

**Comment by chemphys** [comment]
Solved
