### ISSUE TITLE
Missing notebook

### ISSUE THREAD

**Issue by chemphys** [paesanilab/potential_fitting#48]
Hey @zonca ,

The notebook that is [here](https://github.com/paesanilab/potential_fitting/blob/master/fitting/1B/get_codes/generate_fit_notebook/generate_fitting_notebook.ipynb) is the notebook I wrote. COuld you please merge it with your notebook? In this way, if anything needs to be changed, we can simply modify the notebook and download it. 

I am asking this because I added new possible (exp0 and coul0) variables for the polynomials, and in order to make the script work again I had to change several type things. That would make things easier in the future.

Thanks!

**Comment by zonca** [comment]
Which "my notebook" are you referring to?

**Comment by chemphys** [comment]
The one in the link in the previous comment. I assume you wrote a notebook for the new python script ([get-1b-fit.py](https://github.com/paesanilab/potential_fitting/blob/master/fitting/1B/get_codes/get-1b-fit.py)) .

**Comment by zonca** [comment]
I didn't write any notebook and I didn't write `get-1b-fit.py`

**Comment by chemphys** [comment]
Then I will take care of it.

**Comment by chemphys** [comment]
solved
