### ISSUE TITLE
QM MB energy calculator: add fragment information to settings.ini

### ISSUE THREAD

**Issue by agoetz** [paesanilab/potential_fitting#55]
Fragment information should be set by the user in settings.ini. This should include lists with number of atoms per fragment, charges of fragments, and spin multiplicity of fragments. Defaults should be
- Only one fragment, in which case the number of atoms defaults to the value from the xyz file
- charge zero on each fragment
- spin multiplicity one on each fragment

**Comment by EthanBullVulpe** [comment]
I think there should be no defaults here. These are all very important to values, so we should make the user set them directly.

In my opinion, the use of defaults only makes sense for options that will not break the code when invalid. (IE: number of threads or memory for psi4, log file location, etc).

**Comment by agoetz** [comment]
OK, we can make these mandatory.

**Comment by EthanBullVulpe** [comment]
Closing because this is completed at least in qm_mb_calculator.
