### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by agoetz** [paesanilab/potential_fitting#58]
Implement a database that stores molecular information that is required to fit 1B, 2B and 3B potential energy functions.

I suggest to use sqlite3. It is simple to use, has python API, and command line tools on mac and linux by default installed. sqlite3 can directly access database files: open, access/modify, close. No need to run a database server, hence less involved than MongoDB. We can store objects as blob after serializing with pickle.

- Entries in the database should be generated by our configuration generators
- QM MB energy calculator should update the database with energies
- A separate code should access the database to create training set files

**Comment by EthanBullVulpe** [comment]
This is done as far as sqlite3 is concerned.

**Comment by agoetz** [comment]
Great. Let's keep this issue open until the code is merged.
