### ISSUE TITLE
Generate molecule positions

### ISSUE THREAD

**Issue by zonca** [paesanilab/potential_fitting#6]
@sebrown1 can you create a pull request of your code to a new folder in this repo?

**Comment by sebrown1** [comment]
I'm just adding some comments and an example and should have this available in a day or so.
Thanks,Sandra 

    On Wednesday, August 30, 2017 9:57 AM, Andrea Zonca <notifications@github.com> wrote:
 

 @sebrown1 do you have any update on the configuration generation? Any estimate of when a first version will be available?—

**Comment by zonca** [comment]
being implemented in #16

**Comment by zonca** [comment]
merged in #16 testing in #27
