### ISSUE TITLE
Restructure project into python modules.

### ISSUE THREAD

**Issue by EthanBullVulpe** [paesanilab/potential_fitting#77]
Reorganize the files in this project into python modules in a structure that makes sense and is easy to use.

Move all non-python codes into one directory outside the python module.

**Comment by EthanBullVulpe** [comment]
@agoetz I found this example project hierarchy online, what do you think about using something simple for our code?

helloworld/
│
├── bin/ # this directory contains all of our non-python scripts such as the Fortran and C ones.
│
│
├── helloworld/ # this is the main package of our project that users would import
│   ├── __init__.py
│   ├── runner.py # main linking file of our package
│   ├── README.md
│   ├── hello/ # some subpackage
│   │   ├── __init__.py
│   │   ├── hello.py
│   │   ├── helpers.py
│   │   └── README.md
│   │
│   └── world/ # another subpackage
│       ├── __init__.py
│       ├── helpers.py
│       ├── world.py
│       └── README.md
│
│
├── tests/ # module for all of our tests with a directory structure mirroring that of the main module with tests at the appropriate locations
│   ├── hello
│   │   ├── helpers_tests.py
│   │   └── hello_tests.py
│   │
│   └── world/
│       ├── helpers_tests.py
│       └── world_tests.py
│
├── LICENSE # whatever license we choose
└── README.md # file with broad instructions for use of our package as a whole.

**Comment by agoetz** [comment]
Have a look also at this, useful template for new python projects, and an inspiration on structure for existing python projects
https://github.com/choderalab/cookiecutter-compchem

Partly based on the MolSSI Python Template:
https://github.com/MolSSI/python_template

See also
https://github.com/audreyr/cookiecutter
